- hosts: localhost
  become: true
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: cristoto
          oh_my_zsh:
            theme: agnoster
            plugins:
              - git
    - role: geerlingguy.nodejs
    - role: oefenweb.yarn
    - role: geerlingguy.docker
    - role: oefenweb.virtualbox

  tasks:
    - name: Install necesaries programs
      apt: name={{item}}
      with_items:
        - curl
        - git
        - flamerobin

    - name: Install Mozilla Firefox
      snap:
        name: firefox

    - name: Install dbeaver-ce
      snap:
        name: dbeaver-ce

    - name: Install keepassxc
      snap:
        name: keepassxc

    - name: Install Microsoft Teams
      snap:
        name: teams-for-linux

    - name: Install Visual Studio Code
      snap:
        name: code
